DROP TABLE IF EXISTS Coffees;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Projects;
DROP TABLE IF EXISTS Manengers;
DROP TABLE IF EXISTS Companies;
DROP TABLE IF EXISTS Boats;
DROP TABLE IF EXISTS Rentals;
DROP TABLE IF EXISTS Zip;
DROP TABLE IF EXISTS People;

CREATE TABLE People (
    PID INT NOT NULL,
    PN VARCHAR(50) NOT NULL,
    BY INT NOT NULL,
    S VARCHAR(50) NOT NULL,
    PRIMARY KEY (PID)
);

CREATE TABLE Zip(
    Zip INT NOT NULL,
    City VARCHAR(50) NOT NULL,
    PRIMARY KEY (Zip)
);

CREATE TABLE Rentals (
       HID INT NOT NULL, 
       PID INT NOT NULL,
       HS VARCHAR(50) NOT NULL,
       HZ INT NOT NULL,
       PRIMARY KEY (HID),
       FOREIGN KEY (PID) REFERENCES People (PID),
       FOREIGN KEY (HZ) REFERENCES Zip (Zip)
);

CREATE TABLE Boats (
    Z INT NOT NULL,
	BL CHAR(2), 
	BNo INT, 
	BN VARCHAR(50), 
	SSN CHAR(10),
	PRIMARY KEY (Z),
    FOREIGN KEY (Z) REFERENCES Zip (Zip)
);

CREATE TABLE Companies (
    CID INT NOT NULL,
    CN VARCHAR(50) NOT NULL,
    PRIMARY KEY (CID)
);

CREATE TABLE Manengers (
    MID INT NOT NULL,
    MN VARCHAR(50) NOT NULL,
    PRIMARY KEY (MID)
);

CREATE TABLE Projects (
       PID INT NOT NULL, 
       SID INT NOT NULL, 
       MID INT NOT NULL, 
       PN VARCHAR(50) NOT NULL,
       PRIMARY KEY (PID, SID),
       FOREIGN KEY (SID) REFERENCES Companies (CID),
       FOREIGN KEY (MID) REFERENCES Manengers (MID)
);

CREATE TABLE Customers (
       CID INT NOT NULL,
       CNr INT NOT NULL,
       CZ INT NOT NULL,
       EID INT NOT NULL,
       PRIMARY KEY (CID),
       FOREIGN KEY (CID) REFERENCES People (PID),
       FOREIGN KEY (CZ) REFERENCES Zip (Zip)
);

CREATE TABLE Coffees (
       CID INT NOT NULL,
       DID INT NOT NULL,
       HID INT NOT NULL, 
       CN VARCHAR(50) NOT NULL,
       PRIMARY KEY (CID),
       FOREIGN KEY (DID) REFERENCES Customers (CID),
       FOREIGN KEY (CID) REFERENCES Companies (CID)
);
